CREATE TABLE IF NOT EXISTS `#__email_submissions` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NOT NULL,
	`date` DATETIME NOT NULL,

  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
