CREATE TABLE IF NOT EXISTS `#__team_donation_types` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`parent_id` INT(11) NOT NULL,
	`name` VARCHAR(1000) NOT NULL,
	`name_en` VARCHAR(1000) NOT NULL,
	`published` TINYINT(2) NOT NULL,
 
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;